name: PlayerFlow
main: org.kitteh.playerflow.PlayerFlowPlugin
version: 3.0
website: http://kitteh.org
author: mbaxter
description: Replacement for pesky player joined/quit messages
permissions:
  playerflow.receiveperuser:
    description: Receive the usual message every time a player joins or quits
  playerflow.silent:
    description: Does not show up in any alerts or statistics